'use strict'

const ukPoliceForces = [
    {value: 'Avon and Somerset Constabulary', label: 'Avon and Somerset Constabulary'},
    {value: 'Bedfordshire Police', label: 'Bedfordshire Police'},
    {value: 'Cambridgeshire Constabulary', label: 'Cambridgeshire Constabulary'},
    {value: 'Cheshire Constabulary', label: 'Cheshire Constabulary'},
    {value: 'City of London Police', label: 'City of London Police'},
    {value: 'Cleveland Police', label: 'Cleveland Police'},
    {value: 'Cumbria Constabulary', label: 'Cumbria Constabulary'},
    {value: 'Derbyshire Constabulary', label: 'Derbyshire Constabulary'},
    {value: 'Devon and Cornwall Police', label: 'Devon and Cornwall Police'},
    {value: 'Dorset Police', label: 'Dorset Police'},
    {value: 'Durham Constabulary', label: 'Durham Constabulary'},
    {value: 'Dyfed-Powys Police', label: 'Dyfed-Powys Police'},
    {value: 'Essex Police', label: 'Essex Police'},
    {value: 'Gloucestershire Constabulary', label: 'Gloucestershire Constabulary'},
    {value: 'Greater Manchester Police', label: 'Greater Manchester Police'},
    {value: 'Gwent Police', label: 'Gwent Police'},
    {value: 'Hampshire Constabulary', label: 'Hampshire Constabulary'},
    {value: 'Hertfordshire Constabulary', label: 'Hertfordshire Constabulary'},
    {value: 'Humberside Police', label: 'Humberside Police'},
    {value: 'Kent Police', label: 'Kent Police'},
    {value: 'Lancashire Constabulary', label: 'Lancashire Constabulary'},
    {value: 'Leicestershire Police', label: 'Leicestershire Police'},
    {value: 'Lincolnshire Police', label: 'Lincolnshire Police'},
    {value: 'Merseyside Police', label: 'Merseyside Police'},
    {value: 'Metropolitan Police Service', label: 'Metropolitan Police Service'},
    {value: 'Norfolk Constabulary', label: 'Norfolk Constabulary'},
    {value: 'North Yorkshire Police', label: 'North Yorkshire Police'},
    {value: 'North Wales Police', label: 'North Wales Police'},
    {value: 'South Wales Police', label: 'South Wales Police'},
    {value: 'Northamptonshire Police', label: 'Northamptonshire Police'},
    {value: 'Police Service of Northern Ireland', label: 'Police Service of Northern Ireland'},
    {value: 'Police Scotland', label: 'Police Scotland'},
    {value: 'South Yorkshire Police', label: 'South Yorkshire Police'},
    {value: 'Staffordshire Police', label: 'Staffordshire Police'},
    {value: 'Suffolk Constabulary', label: 'Suffolk Constabulary'},
    {value: 'Surrey Police', label: 'Surrey Police'},
    {value: 'Sussex Police', label: 'Sussex Police'},
    {value: 'Thames Valley Police', label: 'Thames Valley Police'},
    {value: 'Warwickshire Police', label: 'Warwickshire Police'},
    {value: 'West Mercia Police', label: 'West Mercia Police'},
    {value: 'West Midlands Police', label: 'West Midlands Police'},
    {value: 'West Yorkshire Police', label: 'West Yorkshire Police'},
    {value: 'Wiltshire Police', label: 'Wiltshire Police'},
    {value: 'British Transport Police', label: 'British Transport Police'},
    {value: 'Civil Nuclear Constabulary', label: 'Civil Nuclear Constabulary'},
    {value: 'Ministry of Defence Police', label: 'Ministry of Defence Police'},
    {value: 'National Police Air Service', label: 'National Police Air Service'},
  ];

  module.exports = ukPoliceForces;
